package com.glodon.demo.mybatis.mappers;

import com.glodon.demo.mybatis.models.CLXYJH;

public interface CLXYJHMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clxyjh
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clxyjh
     *
     * @mbggenerated
     */
    int insert(CLXYJH record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clxyjh
     *
     * @mbggenerated
     */
    int insertSelective(CLXYJH record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clxyjh
     *
     * @mbggenerated
     */
    CLXYJH selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clxyjh
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CLXYJH record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clxyjh
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CLXYJH record);
}