package com.glodon.demo.mybatis.models;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CLXYJHCLMXExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clxyjhclmx
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clxyjhclmx
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clxyjhclmx
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clxyjhclmx
     *
     * @mbggenerated
     */
    public CLXYJHCLMXExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clxyjhclmx
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clxyjhclmx
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clxyjhclmx
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clxyjhclmx
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clxyjhclmx
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clxyjhclmx
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clxyjhclmx
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clxyjhclmx
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clxyjhclmx
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clxyjhclmx
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clxyjhclmx
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andClxyjhidIsNull() {
            addCriterion("clxyjhid is null");
            return (Criteria) this;
        }

        public Criteria andClxyjhidIsNotNull() {
            addCriterion("clxyjhid is not null");
            return (Criteria) this;
        }

        public Criteria andClxyjhidEqualTo(Long value) {
            addCriterion("clxyjhid =", value, "clxyjhid");
            return (Criteria) this;
        }

        public Criteria andClxyjhidNotEqualTo(Long value) {
            addCriterion("clxyjhid <>", value, "clxyjhid");
            return (Criteria) this;
        }

        public Criteria andClxyjhidGreaterThan(Long value) {
            addCriterion("clxyjhid >", value, "clxyjhid");
            return (Criteria) this;
        }

        public Criteria andClxyjhidGreaterThanOrEqualTo(Long value) {
            addCriterion("clxyjhid >=", value, "clxyjhid");
            return (Criteria) this;
        }

        public Criteria andClxyjhidLessThan(Long value) {
            addCriterion("clxyjhid <", value, "clxyjhid");
            return (Criteria) this;
        }

        public Criteria andClxyjhidLessThanOrEqualTo(Long value) {
            addCriterion("clxyjhid <=", value, "clxyjhid");
            return (Criteria) this;
        }

        public Criteria andClxyjhidIn(List<Long> values) {
            addCriterion("clxyjhid in", values, "clxyjhid");
            return (Criteria) this;
        }

        public Criteria andClxyjhidNotIn(List<Long> values) {
            addCriterion("clxyjhid not in", values, "clxyjhid");
            return (Criteria) this;
        }

        public Criteria andClxyjhidBetween(Long value1, Long value2) {
            addCriterion("clxyjhid between", value1, value2, "clxyjhid");
            return (Criteria) this;
        }

        public Criteria andClxyjhidNotBetween(Long value1, Long value2) {
            addCriterion("clxyjhid not between", value1, value2, "clxyjhid");
            return (Criteria) this;
        }

        public Criteria andClzdidIsNull() {
            addCriterion("clzdid is null");
            return (Criteria) this;
        }

        public Criteria andClzdidIsNotNull() {
            addCriterion("clzdid is not null");
            return (Criteria) this;
        }

        public Criteria andClzdidEqualTo(Long value) {
            addCriterion("clzdid =", value, "clzdid");
            return (Criteria) this;
        }

        public Criteria andClzdidNotEqualTo(Long value) {
            addCriterion("clzdid <>", value, "clzdid");
            return (Criteria) this;
        }

        public Criteria andClzdidGreaterThan(Long value) {
            addCriterion("clzdid >", value, "clzdid");
            return (Criteria) this;
        }

        public Criteria andClzdidGreaterThanOrEqualTo(Long value) {
            addCriterion("clzdid >=", value, "clzdid");
            return (Criteria) this;
        }

        public Criteria andClzdidLessThan(Long value) {
            addCriterion("clzdid <", value, "clzdid");
            return (Criteria) this;
        }

        public Criteria andClzdidLessThanOrEqualTo(Long value) {
            addCriterion("clzdid <=", value, "clzdid");
            return (Criteria) this;
        }

        public Criteria andClzdidIn(List<Long> values) {
            addCriterion("clzdid in", values, "clzdid");
            return (Criteria) this;
        }

        public Criteria andClzdidNotIn(List<Long> values) {
            addCriterion("clzdid not in", values, "clzdid");
            return (Criteria) this;
        }

        public Criteria andClzdidBetween(Long value1, Long value2) {
            addCriterion("clzdid between", value1, value2, "clzdid");
            return (Criteria) this;
        }

        public Criteria andClzdidNotBetween(Long value1, Long value2) {
            addCriterion("clzdid not between", value1, value2, "clzdid");
            return (Criteria) this;
        }

        public Criteria andDwIsNull() {
            addCriterion("DW is null");
            return (Criteria) this;
        }

        public Criteria andDwIsNotNull() {
            addCriterion("DW is not null");
            return (Criteria) this;
        }

        public Criteria andDwEqualTo(String value) {
            addCriterion("DW =", value, "dw");
            return (Criteria) this;
        }

        public Criteria andDwNotEqualTo(String value) {
            addCriterion("DW <>", value, "dw");
            return (Criteria) this;
        }

        public Criteria andDwGreaterThan(String value) {
            addCriterion("DW >", value, "dw");
            return (Criteria) this;
        }

        public Criteria andDwGreaterThanOrEqualTo(String value) {
            addCriterion("DW >=", value, "dw");
            return (Criteria) this;
        }

        public Criteria andDwLessThan(String value) {
            addCriterion("DW <", value, "dw");
            return (Criteria) this;
        }

        public Criteria andDwLessThanOrEqualTo(String value) {
            addCriterion("DW <=", value, "dw");
            return (Criteria) this;
        }

        public Criteria andDwLike(String value) {
            addCriterion("DW like", value, "dw");
            return (Criteria) this;
        }

        public Criteria andDwNotLike(String value) {
            addCriterion("DW not like", value, "dw");
            return (Criteria) this;
        }

        public Criteria andDwIn(List<String> values) {
            addCriterion("DW in", values, "dw");
            return (Criteria) this;
        }

        public Criteria andDwNotIn(List<String> values) {
            addCriterion("DW not in", values, "dw");
            return (Criteria) this;
        }

        public Criteria andDwBetween(String value1, String value2) {
            addCriterion("DW between", value1, value2, "dw");
            return (Criteria) this;
        }

        public Criteria andDwNotBetween(String value1, String value2) {
            addCriterion("DW not between", value1, value2, "dw");
            return (Criteria) this;
        }

        public Criteria andBwmcidIsNull() {
            addCriterion("BWMCID is null");
            return (Criteria) this;
        }

        public Criteria andBwmcidIsNotNull() {
            addCriterion("BWMCID is not null");
            return (Criteria) this;
        }

        public Criteria andBwmcidEqualTo(Long value) {
            addCriterion("BWMCID =", value, "bwmcid");
            return (Criteria) this;
        }

        public Criteria andBwmcidNotEqualTo(Long value) {
            addCriterion("BWMCID <>", value, "bwmcid");
            return (Criteria) this;
        }

        public Criteria andBwmcidGreaterThan(Long value) {
            addCriterion("BWMCID >", value, "bwmcid");
            return (Criteria) this;
        }

        public Criteria andBwmcidGreaterThanOrEqualTo(Long value) {
            addCriterion("BWMCID >=", value, "bwmcid");
            return (Criteria) this;
        }

        public Criteria andBwmcidLessThan(Long value) {
            addCriterion("BWMCID <", value, "bwmcid");
            return (Criteria) this;
        }

        public Criteria andBwmcidLessThanOrEqualTo(Long value) {
            addCriterion("BWMCID <=", value, "bwmcid");
            return (Criteria) this;
        }

        public Criteria andBwmcidIn(List<Long> values) {
            addCriterion("BWMCID in", values, "bwmcid");
            return (Criteria) this;
        }

        public Criteria andBwmcidNotIn(List<Long> values) {
            addCriterion("BWMCID not in", values, "bwmcid");
            return (Criteria) this;
        }

        public Criteria andBwmcidBetween(Long value1, Long value2) {
            addCriterion("BWMCID between", value1, value2, "bwmcid");
            return (Criteria) this;
        }

        public Criteria andBwmcidNotBetween(Long value1, Long value2) {
            addCriterion("BWMCID not between", value1, value2, "bwmcid");
            return (Criteria) this;
        }

        public Criteria andBwmcIsNull() {
            addCriterion("BWMC is null");
            return (Criteria) this;
        }

        public Criteria andBwmcIsNotNull() {
            addCriterion("BWMC is not null");
            return (Criteria) this;
        }

        public Criteria andBwmcEqualTo(Long value) {
            addCriterion("BWMC =", value, "bwmc");
            return (Criteria) this;
        }

        public Criteria andBwmcNotEqualTo(Long value) {
            addCriterion("BWMC <>", value, "bwmc");
            return (Criteria) this;
        }

        public Criteria andBwmcGreaterThan(Long value) {
            addCriterion("BWMC >", value, "bwmc");
            return (Criteria) this;
        }

        public Criteria andBwmcGreaterThanOrEqualTo(Long value) {
            addCriterion("BWMC >=", value, "bwmc");
            return (Criteria) this;
        }

        public Criteria andBwmcLessThan(Long value) {
            addCriterion("BWMC <", value, "bwmc");
            return (Criteria) this;
        }

        public Criteria andBwmcLessThanOrEqualTo(Long value) {
            addCriterion("BWMC <=", value, "bwmc");
            return (Criteria) this;
        }

        public Criteria andBwmcIn(List<Long> values) {
            addCriterion("BWMC in", values, "bwmc");
            return (Criteria) this;
        }

        public Criteria andBwmcNotIn(List<Long> values) {
            addCriterion("BWMC not in", values, "bwmc");
            return (Criteria) this;
        }

        public Criteria andBwmcBetween(Long value1, Long value2) {
            addCriterion("BWMC between", value1, value2, "bwmc");
            return (Criteria) this;
        }

        public Criteria andBwmcNotBetween(Long value1, Long value2) {
            addCriterion("BWMC not between", value1, value2, "bwmc");
            return (Criteria) this;
        }

        public Criteria andBwmcfulldescIsNull() {
            addCriterion("BWMCFULLDesc is null");
            return (Criteria) this;
        }

        public Criteria andBwmcfulldescIsNotNull() {
            addCriterion("BWMCFULLDesc is not null");
            return (Criteria) this;
        }

        public Criteria andBwmcfulldescEqualTo(String value) {
            addCriterion("BWMCFULLDesc =", value, "bwmcfulldesc");
            return (Criteria) this;
        }

        public Criteria andBwmcfulldescNotEqualTo(String value) {
            addCriterion("BWMCFULLDesc <>", value, "bwmcfulldesc");
            return (Criteria) this;
        }

        public Criteria andBwmcfulldescGreaterThan(String value) {
            addCriterion("BWMCFULLDesc >", value, "bwmcfulldesc");
            return (Criteria) this;
        }

        public Criteria andBwmcfulldescGreaterThanOrEqualTo(String value) {
            addCriterion("BWMCFULLDesc >=", value, "bwmcfulldesc");
            return (Criteria) this;
        }

        public Criteria andBwmcfulldescLessThan(String value) {
            addCriterion("BWMCFULLDesc <", value, "bwmcfulldesc");
            return (Criteria) this;
        }

        public Criteria andBwmcfulldescLessThanOrEqualTo(String value) {
            addCriterion("BWMCFULLDesc <=", value, "bwmcfulldesc");
            return (Criteria) this;
        }

        public Criteria andBwmcfulldescLike(String value) {
            addCriterion("BWMCFULLDesc like", value, "bwmcfulldesc");
            return (Criteria) this;
        }

        public Criteria andBwmcfulldescNotLike(String value) {
            addCriterion("BWMCFULLDesc not like", value, "bwmcfulldesc");
            return (Criteria) this;
        }

        public Criteria andBwmcfulldescIn(List<String> values) {
            addCriterion("BWMCFULLDesc in", values, "bwmcfulldesc");
            return (Criteria) this;
        }

        public Criteria andBwmcfulldescNotIn(List<String> values) {
            addCriterion("BWMCFULLDesc not in", values, "bwmcfulldesc");
            return (Criteria) this;
        }

        public Criteria andBwmcfulldescBetween(String value1, String value2) {
            addCriterion("BWMCFULLDesc between", value1, value2, "bwmcfulldesc");
            return (Criteria) this;
        }

        public Criteria andBwmcfulldescNotBetween(String value1, String value2) {
            addCriterion("BWMCFULLDesc not between", value1, value2, "bwmcfulldesc");
            return (Criteria) this;
        }

        public Criteria andJhlIsNull() {
            addCriterion("JHL is null");
            return (Criteria) this;
        }

        public Criteria andJhlIsNotNull() {
            addCriterion("JHL is not null");
            return (Criteria) this;
        }

        public Criteria andJhlEqualTo(BigDecimal value) {
            addCriterion("JHL =", value, "jhl");
            return (Criteria) this;
        }

        public Criteria andJhlNotEqualTo(BigDecimal value) {
            addCriterion("JHL <>", value, "jhl");
            return (Criteria) this;
        }

        public Criteria andJhlGreaterThan(BigDecimal value) {
            addCriterion("JHL >", value, "jhl");
            return (Criteria) this;
        }

        public Criteria andJhlGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("JHL >=", value, "jhl");
            return (Criteria) this;
        }

        public Criteria andJhlLessThan(BigDecimal value) {
            addCriterion("JHL <", value, "jhl");
            return (Criteria) this;
        }

        public Criteria andJhlLessThanOrEqualTo(BigDecimal value) {
            addCriterion("JHL <=", value, "jhl");
            return (Criteria) this;
        }

        public Criteria andJhlIn(List<BigDecimal> values) {
            addCriterion("JHL in", values, "jhl");
            return (Criteria) this;
        }

        public Criteria andJhlNotIn(List<BigDecimal> values) {
            addCriterion("JHL not in", values, "jhl");
            return (Criteria) this;
        }

        public Criteria andJhlBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("JHL between", value1, value2, "jhl");
            return (Criteria) this;
        }

        public Criteria andJhlNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("JHL not between", value1, value2, "jhl");
            return (Criteria) this;
        }

        public Criteria andJhrqIsNull() {
            addCriterion("JHRQ is null");
            return (Criteria) this;
        }

        public Criteria andJhrqIsNotNull() {
            addCriterion("JHRQ is not null");
            return (Criteria) this;
        }

        public Criteria andJhrqEqualTo(Date value) {
            addCriterion("JHRQ =", value, "jhrq");
            return (Criteria) this;
        }

        public Criteria andJhrqNotEqualTo(Date value) {
            addCriterion("JHRQ <>", value, "jhrq");
            return (Criteria) this;
        }

        public Criteria andJhrqGreaterThan(Date value) {
            addCriterion("JHRQ >", value, "jhrq");
            return (Criteria) this;
        }

        public Criteria andJhrqGreaterThanOrEqualTo(Date value) {
            addCriterion("JHRQ >=", value, "jhrq");
            return (Criteria) this;
        }

        public Criteria andJhrqLessThan(Date value) {
            addCriterion("JHRQ <", value, "jhrq");
            return (Criteria) this;
        }

        public Criteria andJhrqLessThanOrEqualTo(Date value) {
            addCriterion("JHRQ <=", value, "jhrq");
            return (Criteria) this;
        }

        public Criteria andJhrqIn(List<Date> values) {
            addCriterion("JHRQ in", values, "jhrq");
            return (Criteria) this;
        }

        public Criteria andJhrqNotIn(List<Date> values) {
            addCriterion("JHRQ not in", values, "jhrq");
            return (Criteria) this;
        }

        public Criteria andJhrqBetween(Date value1, Date value2) {
            addCriterion("JHRQ between", value1, value2, "jhrq");
            return (Criteria) this;
        }

        public Criteria andJhrqNotBetween(Date value1, Date value2) {
            addCriterion("JHRQ not between", value1, value2, "jhrq");
            return (Criteria) this;
        }

        public Criteria andZlyqIsNull() {
            addCriterion("ZLYQ is null");
            return (Criteria) this;
        }

        public Criteria andZlyqIsNotNull() {
            addCriterion("ZLYQ is not null");
            return (Criteria) this;
        }

        public Criteria andZlyqEqualTo(String value) {
            addCriterion("ZLYQ =", value, "zlyq");
            return (Criteria) this;
        }

        public Criteria andZlyqNotEqualTo(String value) {
            addCriterion("ZLYQ <>", value, "zlyq");
            return (Criteria) this;
        }

        public Criteria andZlyqGreaterThan(String value) {
            addCriterion("ZLYQ >", value, "zlyq");
            return (Criteria) this;
        }

        public Criteria andZlyqGreaterThanOrEqualTo(String value) {
            addCriterion("ZLYQ >=", value, "zlyq");
            return (Criteria) this;
        }

        public Criteria andZlyqLessThan(String value) {
            addCriterion("ZLYQ <", value, "zlyq");
            return (Criteria) this;
        }

        public Criteria andZlyqLessThanOrEqualTo(String value) {
            addCriterion("ZLYQ <=", value, "zlyq");
            return (Criteria) this;
        }

        public Criteria andZlyqLike(String value) {
            addCriterion("ZLYQ like", value, "zlyq");
            return (Criteria) this;
        }

        public Criteria andZlyqNotLike(String value) {
            addCriterion("ZLYQ not like", value, "zlyq");
            return (Criteria) this;
        }

        public Criteria andZlyqIn(List<String> values) {
            addCriterion("ZLYQ in", values, "zlyq");
            return (Criteria) this;
        }

        public Criteria andZlyqNotIn(List<String> values) {
            addCriterion("ZLYQ not in", values, "zlyq");
            return (Criteria) this;
        }

        public Criteria andZlyqBetween(String value1, String value2) {
            addCriterion("ZLYQ between", value1, value2, "zlyq");
            return (Criteria) this;
        }

        public Criteria andZlyqNotBetween(String value1, String value2) {
            addCriterion("ZLYQ not between", value1, value2, "zlyq");
            return (Criteria) this;
        }

        public Criteria andPpIsNull() {
            addCriterion("PP is null");
            return (Criteria) this;
        }

        public Criteria andPpIsNotNull() {
            addCriterion("PP is not null");
            return (Criteria) this;
        }

        public Criteria andPpEqualTo(String value) {
            addCriterion("PP =", value, "pp");
            return (Criteria) this;
        }

        public Criteria andPpNotEqualTo(String value) {
            addCriterion("PP <>", value, "pp");
            return (Criteria) this;
        }

        public Criteria andPpGreaterThan(String value) {
            addCriterion("PP >", value, "pp");
            return (Criteria) this;
        }

        public Criteria andPpGreaterThanOrEqualTo(String value) {
            addCriterion("PP >=", value, "pp");
            return (Criteria) this;
        }

        public Criteria andPpLessThan(String value) {
            addCriterion("PP <", value, "pp");
            return (Criteria) this;
        }

        public Criteria andPpLessThanOrEqualTo(String value) {
            addCriterion("PP <=", value, "pp");
            return (Criteria) this;
        }

        public Criteria andPpLike(String value) {
            addCriterion("PP like", value, "pp");
            return (Criteria) this;
        }

        public Criteria andPpNotLike(String value) {
            addCriterion("PP not like", value, "pp");
            return (Criteria) this;
        }

        public Criteria andPpIn(List<String> values) {
            addCriterion("PP in", values, "pp");
            return (Criteria) this;
        }

        public Criteria andPpNotIn(List<String> values) {
            addCriterion("PP not in", values, "pp");
            return (Criteria) this;
        }

        public Criteria andPpBetween(String value1, String value2) {
            addCriterion("PP between", value1, value2, "pp");
            return (Criteria) this;
        }

        public Criteria andPpNotBetween(String value1, String value2) {
            addCriterion("PP not between", value1, value2, "pp");
            return (Criteria) this;
        }

        public Criteria andGhddIsNull() {
            addCriterion("GHDD is null");
            return (Criteria) this;
        }

        public Criteria andGhddIsNotNull() {
            addCriterion("GHDD is not null");
            return (Criteria) this;
        }

        public Criteria andGhddEqualTo(String value) {
            addCriterion("GHDD =", value, "ghdd");
            return (Criteria) this;
        }

        public Criteria andGhddNotEqualTo(String value) {
            addCriterion("GHDD <>", value, "ghdd");
            return (Criteria) this;
        }

        public Criteria andGhddGreaterThan(String value) {
            addCriterion("GHDD >", value, "ghdd");
            return (Criteria) this;
        }

        public Criteria andGhddGreaterThanOrEqualTo(String value) {
            addCriterion("GHDD >=", value, "ghdd");
            return (Criteria) this;
        }

        public Criteria andGhddLessThan(String value) {
            addCriterion("GHDD <", value, "ghdd");
            return (Criteria) this;
        }

        public Criteria andGhddLessThanOrEqualTo(String value) {
            addCriterion("GHDD <=", value, "ghdd");
            return (Criteria) this;
        }

        public Criteria andGhddLike(String value) {
            addCriterion("GHDD like", value, "ghdd");
            return (Criteria) this;
        }

        public Criteria andGhddNotLike(String value) {
            addCriterion("GHDD not like", value, "ghdd");
            return (Criteria) this;
        }

        public Criteria andGhddIn(List<String> values) {
            addCriterion("GHDD in", values, "ghdd");
            return (Criteria) this;
        }

        public Criteria andGhddNotIn(List<String> values) {
            addCriterion("GHDD not in", values, "ghdd");
            return (Criteria) this;
        }

        public Criteria andGhddBetween(String value1, String value2) {
            addCriterion("GHDD between", value1, value2, "ghdd");
            return (Criteria) this;
        }

        public Criteria andGhddNotBetween(String value1, String value2) {
            addCriterion("GHDD not between", value1, value2, "ghdd");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clxyjhclmx
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clxyjhclmx
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}