package com.glodon.demo.mybatis.models;

import java.math.BigDecimal;
import java.util.Date;

public class CLXYJHCLMX {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clxyjhclmx.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clxyjhclmx.clxyjhid
     *
     * @mbggenerated
     */
    private Long clxyjhid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clxyjhclmx.clzdid
     *
     * @mbggenerated
     */
    private Long clzdid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clxyjhclmx.DW
     *
     * @mbggenerated
     */
    private String dw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clxyjhclmx.BWMCID
     *
     * @mbggenerated
     */
    private Long bwmcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clxyjhclmx.BWMC
     *
     * @mbggenerated
     */
    private Long bwmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clxyjhclmx.BWMCFULLDesc
     *
     * @mbggenerated
     */
    private String bwmcfulldesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clxyjhclmx.JHL
     *
     * @mbggenerated
     */
    private BigDecimal jhl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clxyjhclmx.JHRQ
     *
     * @mbggenerated
     */
    private Date jhrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clxyjhclmx.ZLYQ
     *
     * @mbggenerated
     */
    private String zlyq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clxyjhclmx.PP
     *
     * @mbggenerated
     */
    private String pp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clxyjhclmx.GHDD
     *
     * @mbggenerated
     */
    private String ghdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clxyjhclmx.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clxyjhclmx.id
     *
     * @return the value of clxyjhclmx.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clxyjhclmx.id
     *
     * @param id the value for clxyjhclmx.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clxyjhclmx.clxyjhid
     *
     * @return the value of clxyjhclmx.clxyjhid
     *
     * @mbggenerated
     */
    public Long getClxyjhid() {
        return clxyjhid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clxyjhclmx.clxyjhid
     *
     * @param clxyjhid the value for clxyjhclmx.clxyjhid
     *
     * @mbggenerated
     */
    public void setClxyjhid(Long clxyjhid) {
        this.clxyjhid = clxyjhid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clxyjhclmx.clzdid
     *
     * @return the value of clxyjhclmx.clzdid
     *
     * @mbggenerated
     */
    public Long getClzdid() {
        return clzdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clxyjhclmx.clzdid
     *
     * @param clzdid the value for clxyjhclmx.clzdid
     *
     * @mbggenerated
     */
    public void setClzdid(Long clzdid) {
        this.clzdid = clzdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clxyjhclmx.DW
     *
     * @return the value of clxyjhclmx.DW
     *
     * @mbggenerated
     */
    public String getDw() {
        return dw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clxyjhclmx.DW
     *
     * @param dw the value for clxyjhclmx.DW
     *
     * @mbggenerated
     */
    public void setDw(String dw) {
        this.dw = dw == null ? null : dw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clxyjhclmx.BWMCID
     *
     * @return the value of clxyjhclmx.BWMCID
     *
     * @mbggenerated
     */
    public Long getBwmcid() {
        return bwmcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clxyjhclmx.BWMCID
     *
     * @param bwmcid the value for clxyjhclmx.BWMCID
     *
     * @mbggenerated
     */
    public void setBwmcid(Long bwmcid) {
        this.bwmcid = bwmcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clxyjhclmx.BWMC
     *
     * @return the value of clxyjhclmx.BWMC
     *
     * @mbggenerated
     */
    public Long getBwmc() {
        return bwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clxyjhclmx.BWMC
     *
     * @param bwmc the value for clxyjhclmx.BWMC
     *
     * @mbggenerated
     */
    public void setBwmc(Long bwmc) {
        this.bwmc = bwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clxyjhclmx.BWMCFULLDesc
     *
     * @return the value of clxyjhclmx.BWMCFULLDesc
     *
     * @mbggenerated
     */
    public String getBwmcfulldesc() {
        return bwmcfulldesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clxyjhclmx.BWMCFULLDesc
     *
     * @param bwmcfulldesc the value for clxyjhclmx.BWMCFULLDesc
     *
     * @mbggenerated
     */
    public void setBwmcfulldesc(String bwmcfulldesc) {
        this.bwmcfulldesc = bwmcfulldesc == null ? null : bwmcfulldesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clxyjhclmx.JHL
     *
     * @return the value of clxyjhclmx.JHL
     *
     * @mbggenerated
     */
    public BigDecimal getJhl() {
        return jhl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clxyjhclmx.JHL
     *
     * @param jhl the value for clxyjhclmx.JHL
     *
     * @mbggenerated
     */
    public void setJhl(BigDecimal jhl) {
        this.jhl = jhl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clxyjhclmx.JHRQ
     *
     * @return the value of clxyjhclmx.JHRQ
     *
     * @mbggenerated
     */
    public Date getJhrq() {
        return jhrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clxyjhclmx.JHRQ
     *
     * @param jhrq the value for clxyjhclmx.JHRQ
     *
     * @mbggenerated
     */
    public void setJhrq(Date jhrq) {
        this.jhrq = jhrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clxyjhclmx.ZLYQ
     *
     * @return the value of clxyjhclmx.ZLYQ
     *
     * @mbggenerated
     */
    public String getZlyq() {
        return zlyq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clxyjhclmx.ZLYQ
     *
     * @param zlyq the value for clxyjhclmx.ZLYQ
     *
     * @mbggenerated
     */
    public void setZlyq(String zlyq) {
        this.zlyq = zlyq == null ? null : zlyq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clxyjhclmx.PP
     *
     * @return the value of clxyjhclmx.PP
     *
     * @mbggenerated
     */
    public String getPp() {
        return pp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clxyjhclmx.PP
     *
     * @param pp the value for clxyjhclmx.PP
     *
     * @mbggenerated
     */
    public void setPp(String pp) {
        this.pp = pp == null ? null : pp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clxyjhclmx.GHDD
     *
     * @return the value of clxyjhclmx.GHDD
     *
     * @mbggenerated
     */
    public String getGhdd() {
        return ghdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clxyjhclmx.GHDD
     *
     * @param ghdd the value for clxyjhclmx.GHDD
     *
     * @mbggenerated
     */
    public void setGhdd(String ghdd) {
        this.ghdd = ghdd == null ? null : ghdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clxyjhclmx.remark
     *
     * @return the value of clxyjhclmx.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clxyjhclmx.remark
     *
     * @param remark the value for clxyjhclmx.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}