package com.glodon.demo.mybatis.models;

import com.glodon.demo.mybatis.enums.JHLX;
import java.util.Date;

public class CLXYJH {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clxyjh.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clxyjh.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clxyjh.bizDate
     *
     * @mbggenerated
     */
    private Date bizdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clxyjh.JHLX
     *
     * @mbggenerated
     */
    private JHLX jhlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clxyjh.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clxyjh.id
     *
     * @return the value of clxyjh.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clxyjh.id
     *
     * @param id the value for clxyjh.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clxyjh.code
     *
     * @return the value of clxyjh.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clxyjh.code
     *
     * @param code the value for clxyjh.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clxyjh.bizDate
     *
     * @return the value of clxyjh.bizDate
     *
     * @mbggenerated
     */
    public Date getBizdate() {
        return bizdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clxyjh.bizDate
     *
     * @param bizdate the value for clxyjh.bizDate
     *
     * @mbggenerated
     */
    public void setBizdate(Date bizdate) {
        this.bizdate = bizdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clxyjh.JHLX
     *
     * @return the value of clxyjh.JHLX
     *
     * @mbggenerated
     */
    public JHLX getJhlx() {
        return jhlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clxyjh.JHLX
     *
     * @param jhlx the value for clxyjh.JHLX
     *
     * @mbggenerated
     */
    public void setJhlx(JHLX jhlx) {
        this.jhlx = jhlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clxyjh.remark
     *
     * @return the value of clxyjh.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clxyjh.remark
     *
     * @param remark the value for clxyjh.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}